# -*- coding: utf-8 -*-
"""linear regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YyYqoEtIm3zZ71cUr6dv4PHkmAkGDkRc
"""

import pandas as pd # Pandas লাইব্রেরি pd নামে ব্যবহার করা (ডেটা ম্যানিপুলেশনের জন্য)
import numpy as np # NumPy লাইব্রেরি np নামে ব্যবহার করা (ম্যাথ, array, matrix operations এর জন্য)
import operator # Python এর operator module ব্যবহার করা (arithmetic, comparison, sorting, etc. সহজে করার

from google.colab import files
files.upload()

data = pd.read_csv('Salary_Data.csv')

data.sample(10) # 👉 ডেটাসেট থেকে র‍্যান্ডমভাবে ১০টি row দেখানো।

data.head(10)

# 👉 ডেটাসেটের প্রথম ১০টি row দেখানো।

# ডিফল্ট হলে head() ৫টি দেখায়, এখানে explicitly ১০ টা চাইছেন।

# ব্যবহার হয় ডেটা দ্রুত পরীক্ষা করার জন্য 👀

data.tail(10)

# 👉 ডেটাসেটের শেষ ১০টি row দেখানো।

# tail() → ডিফল্ট ৫টি row দেখায়

# tail(10) → স্পেসিফিক সংখ্যা (এখানে ১০) row দেখায় ✅

data.describe() # 👉 ডেটাসেটের স্ট্যাটিস্টিকাল summary দেখানো।

data.isnull().sum(axis=0) # 👉 প্রতি কলামে (column-wise) কয়টা করে missing/null value আছে সেটা গুনে দেখানো।

data = data.dropna() # 👉 যেসব row-তে অন্তত একটি null value আছে, সেগুলো পুরো row সহ ডেটা থেকে বাদ দেওয়া।

data = data.head() # 👉 ডেটাসেটের প্রথম ৫টি row নেওয়া (ডিফল্টভাবে)।

import matplotlib.pyplot as plt # 👉 Matplotlib লাইব্রেরির pyplot মডিউলকে plt নামে ব্যবহার করা, গ্রাফ/চার্ট আঁকার জন্য।

plt.scatter(data['YearsExperience'],data['Salary']) # plt.scatter(...) → ডাটা পয়েন্ট আকারে দেখায়
plt.xlabel('YearsExperience') # plt.xlabel(...) → X-axis নাম
plt.ylabel('Salary') # plt.ylabel(...) → Y-axis নাম

exp_avg = data['YearsExperience'].mean() # 👉 YearsExperience আর Salary কলামের গড় (average) মান বের করা।
sal_avg = data['Salary'].mean()

exp_salary = data['YearsExperience']*data['Salary'] # 👉 YearsExperience × Salary এবং YearsExperience এর square হিসাব করা (element-wise)।
exp_sq = data['YearsExperience']*data['YearsExperience']

m = (exp_avg*sal_avg - exp_salary.mean()) / (exp_avg*exp_avg - exp_sq.mean())
c = sal_avg - m*exp_avg


# 👉 Simple Linear Regression এর slope (m) এবং intercept (c) হিসাব করা।

# m → রেখার ঢাল (Salary কতটা Experience-এর সাথে বাড়ে)

# c → Y-intercept (Experience = 0 হলে Salary)

# সংক্ষেপে: best fit straight line বের করা 📈

print(m,c)

exp = input('Enter the years of experience: ')  # 👉 ইউজারের কাছ থেকে Years of Experience ইনপুট নেওয়া ।

print(m*int(exp)+c)

# 👉 ইউজারের দেওয়া অভিজ্ঞতার (exp) উপর ভিত্তি করে Salary প্রেডিকশন করা।

# int(exp) → ইউজারের ইনপুট string কে integer এ কনভার্ট করা

# m*int(exp) + c → Simple Linear Regression formula: Salary = m*Experience + c

# print(...) → প্রেডিক্টেড Salary দেখানো 📈

