# -*- coding: utf-8 -*-
"""Boundary Extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BuM_jytLkE8SeGQszS7cmfApffHdxd_5
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
from google.colab import files

# লোড
img = cv2.imread('lena.jpg', 0)
if img is None:
    files.upload()
    img = cv2.imread('lena.jpg', 0)

# Binary
_, bin = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)

# Erosion
kernel = np.ones((3,3), np.uint8)
ero = cv2.erode(bin, kernel)

# Boundary = Binary - Erosion
boundary = cv2.subtract(bin, ero)

# দেখান
print("Boundary:")
cv2_imshow(boundary)

# ডাউনলোড
cv2.imwrite('boundary.jpg', boundary)
files.download('boundary.jpg')

