# -*- coding: utf-8 -*-
"""image negetive.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13EgshluNhH8kEDD0wv93Q6wXQnNIwqVW
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
from google.colab import files

# লোড
img = cv2.imread('lena.jpg', 0)
if img is None:
    files.upload()
    img = cv2.imread('lena.jpg', 0)

# Negative (২টি পদ্ধতি)
negative1 = 255 - img  # Formula
negative2 = cv2.bitwise_not(img)  # Bitwise NOT

# দেখান
print("Original:")
cv2_imshow(img)
print("Negative (Formula):")
cv2_imshow(negative1)
print("Negative (Bitwise NOT):")
cv2_imshow(negative2)