# -*- coding: utf-8 -*-
"""Inverse log transformation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JKq78rvrw8Y5CkIkFRXHc7pYjNH1De82
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
from google.colab import files

# লোড
img = cv2.imread('domJain.jpg', 0)
if img is None:
    files.upload()
    img = cv2.imread('domJain.jpg', 0)

# Inverse Log Transformation
img_norm = img / 255.0
inverse_log = np.exp(img_norm) - 1
inverse_log = (inverse_log / inverse_log.max()) * 255
inverse_log = inverse_log.astype(np.uint8)

# দেখান
cv2_imshow(img)
cv2_imshow(inverse_log)

# ডাউনলোড
cv2.imwrite('inverse_log.jpg', inverse_log)
files.download('inverse_log.jpg')

