# -*- coding: utf-8 -*-
"""log transformation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CpuwxgAC23kzYsDgeIEM-dh1yXHikzM7
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
from google.colab import files

# লোড
img = cv2.imread('lena.jpg', 0)
if img is None:
    files.upload()
    img = cv2.imread('lena.jpg', 0)

# Log Transformation
img_norm = img / 255.0
log_transform = np.log(1 + img_norm)
log_transform = (log_transform / log_transform.max()) * 255
log_transform = log_transform.astype(np.uint8)

# দেখান
print("Original:")
cv2_imshow(img)
print("Log Transformed:")
cv2_imshow(log_transform)

# ডাউনলোড
cv2.imwrite('log_transform.jpg', log_transform)
files.download('log_transform.jpg')

