# -*- coding: utf-8 -*-
"""Opening Clossing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11DocndmNysMXUTZW8Gj5o50MHmmfc2lo
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
from google.colab import files

# লোড
img = cv2.imread('lena.jpg', 0)
if img is None:
    files.upload()
    img = cv2.imread('lena.jpg', 0)

# Binary
_, bin = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)

# Kernel
k = np.ones((5,5), np.uint8)

# Opening & Closing
op = cv2.morphologyEx(bin, cv2.MORPH_OPEN, k)
cl = cv2.morphologyEx(bin, cv2.MORPH_CLOSE, k)

# দেখান
cv2_imshow(bin) #Binary Image (Original কে থ্রেশহোল্ড করা)
cv2_imshow(op) #Opening Result (Erosion → Dilation)
cv2_imshow(cl) #Closing Result (Dilation → Erosion)

# ডাউনলোড
# cv2.imwrite('op.jpg', op)
# cv2.imwrite('cl.jpg', cl)
# files.download('op.jpg')
# files.download('cl.jpg')

